In [339]:
import pandas as pd

In [340]:
Year = 2026

#### Loading forecasted data from https://www.smartgriddashboard.com/roi/wind/?duration=month&datefrom=28-Dec-2025&dateto=26-Jan-2026

In [341]:
df = pd.read_csv(f'./EirGrid_data/{Year}/Wind_generation_ireland.csv')
df.columns = df.columns.str.strip() 
df["DATE & TIME"] = pd.to_datetime(
        df["DATE & TIME"],
        dayfirst=True,
        errors="raise",        # fail loudly if format is wrong
        format="%d/%m/%Y %H:%M",
        utc=True
    )
df = df.set_index("DATE & TIME")

In [342]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 23325 entries, 2026-01-01 00:00:00+00:00 to 2026-09-01 00:00:00+00:00
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ACTUAL WIND(MW)    23325 non-null  int64
 1   FORECAST WIND(MW)  23325 non-null  int64
 2   Unnamed: 3         23325 non-null  str
dtypes: int64(2), str(1)
memory usage: 728.9 KB

In [343]:
print(df.columns)

Index(['ACTUAL WIND(MW)', 'FORECAST WIND(MW)', 'Unnamed: 3'], dtype='str')

In [344]:
# Hourly average
wind_hourly = df.resample("h").agg({"ACTUAL WIND(MW)": "mean","FORECAST WIND(MW)": "mean"})

In [345]:
wind_hourly

                           ACTUAL WIND(MW)  FORECAST WIND(MW)
DATE & TIME
2026-01-01 00:00:00+00:00          1378.75             964.00
2026-01-01 01:00:00+00:00          1369.25             971.75
2026-01-01 02:00:00+00:00          1501.50            1014.00
2026-01-01 03:00:00+00:00          1549.50            1085.25
2026-01-01 04:00:00+00:00          1410.00            1121.00
...                                    ...                ...
2026-08-31 20:00:00+00:00           871.75             943.00
2026-08-31 21:00:00+00:00           924.75             977.75
2026-08-31 22:00:00+00:00           983.50            1068.00
2026-08-31 23:00:00+00:00          1151.75            1155.25
2026-09-01 00:00:00+00:00          1212.00            1182.00

[5833 rows x 2 columns]

#### Loading weather data from :
https://www.met.ie/climate/available-data/historical-data

In [346]:
weather_hourly= pd.read_csv(f'Met-Eireann_data/{Year}/AggregateData_weather.csv')
weather_hourly["date"] = pd.to_datetime(
        weather_hourly["date"],
        format="%d/%m/%Y %H:%M",
        dayfirst=True,
        errors="raise",
        utc=True
    )

weather_hourly = weather_hourly.set_index("date")

In [347]:
weather_hourly

,irainfall Rainfall indicator,Precipitation Amount (mm),ittt Dry bulb indicator,Air Temperature (C),iwb Wet bulb indicator,Wet Bulb Temperature ©,Dew Point Temperature ©,Vapour Pressure (hPa),Relative Humidity (%),Mean Sea Level Pressure (hPa),itabspeed wind Speed indicator,Mean Wind Speed (kt),itabdir wind dir indicator,Predominant Wind Direction (deg),Weekday,Mean Wind Speed (km/h)
date,,,,,,,,,,,,,,,,
2026-01-01 00:00:00+00:00,0,0.020,0,4.135,0,3.080,1.395,6.810,82.05,1021.700,2,8.666667,2.0,246.111111,1,16.050667
2026-01-01 01:00:00+00:00,0,0.020,0,4.450,0,3.375,1.720,6.975,82.25,1020.755,2,9.111111,2.0,243.888889,1,16.873778
2026-01-01 02:00:00+00:00,0,0.030,0,4.610,0,3.610,2.100,7.155,83.45,1019.655,2,9.055556,2.0,243.333333,1,16.770889
2026-01-01 03:00:00+00:00,0,0.035,0,4.825,0,3.890,2.510,7.365,84.70,1018.815,2,9.500000,2.0,247.222222,1,17.594000
2026-01-01 04:00:00+00:00,0,0.055,0,4.790,0,3.935,2.700,7.460,85.90,1017.935,2,9.444444,2.0,240.000000,1,17.491111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-31 20:00:00+00:00,0,0.035,0,14.620,0,13.000,11.590,13.690,81.90,1017.225,2,7.444444,2.0,229.444444,1,13.787111
2026-08-31 21:00:00+00:00,0,0.020,0,14.180,0,12.765,11.545,13.665,84.05,1017.335,2,7.222222,2.0,222.777778,1,13.375556
2026-08-31 22:00:00+00:00,0,0.005,0,13.850,0,12.655,11.615,13.730,86.15,1017.380,2,6.944444,2.0,201.111111,1,12.861111
2026-08-31 23:00:00+00:00,0,0.025,0,13.905,0,12.825,11.905,13.990,87.50,1017.265,2,7.333333,2.0,203.333333,1,13.581333
2026-09-01 00:00:00+00:00,0,0.010,0,13.910,0,12.835,11.910,14.005,87.50,1016.930,2,7.888889,2.0,206.666667,1,14.610222

#### Loading Entso-e data set

In [348]:
entsoe_actual_generation = pd.read_csv(f'./Entso-e_data/{Year}/actual_generation_ENTSOE.csv')                            
entsoe_forecasted_wind_solar = pd.read_csv(f'./Entso-e_data/{Year}/wind_solar_forecast_ENTSOE.csv')
entsoe_load = pd.read_csv(f'./Entso-e_data/{Year}/load_ENTSOE.csv')
entsoe_load_forecast = pd.read_csv(f'./Entso-e_data/{Year}/load_forecast_ENTSOE.csv')

In [349]:
entsoe_actual_generation = entsoe_actual_generation.set_index("DateTime")
entsoe_actual_generation.index = pd.to_datetime(entsoe_actual_generation.index, utc=True, errors="coerce")

entsoe_forecasted_wind_solar = entsoe_forecasted_wind_solar.set_index("DateTime")
entsoe_forecasted_wind_solar.index = pd.to_datetime(entsoe_forecasted_wind_solar.index, utc=True, errors="coerce")

entsoe_load = entsoe_load.set_index("DateTime")
entsoe_load.index = pd.to_datetime(entsoe_load.index, utc=True, errors="coerce")

entsoe_load_forecast = entsoe_load_forecast.set_index("DateTime")
entsoe_load_forecast.index = pd.to_datetime(entsoe_load_forecast.index, utc=True, errors="coerce")

In [350]:
entsoe_hourly_actual_generation = entsoe_actual_generation.resample("h").mean()
entsoe_hourly_forecasted_wind_solar = entsoe_forecasted_wind_solar.resample("h").mean()
entsoe_hourly_load = entsoe_load.resample("h").mean()
entsoe_hourly_load_forecast = entsoe_load_forecast.resample("h").mean()

#### Merging weather data with generation data

In [351]:
def merge_dataframes_wrt_time(df1, df2, name1="df1", name2="df2"):
    # Ensure both indexes are DatetimeIndex and tz-aware
    df1.index = pd.to_datetime(df1.index, utc=True)
    df2.index = pd.to_datetime(df2.index, utc=True)

    # Extract timestamp sets
    ts1 = set(df1.index)
    ts2 = set(df2.index)

    # Compute missing timestamps
    missing_in_df1 = sorted(ts2 - ts1)
    missing_in_df2 = sorted(ts1 - ts2)

    # Print diagnostics
    print(f"\n=== Timestamp Comparison: {name1} vs {name2} ===")

    if missing_in_df1:
        print(f"\n⚠ Missing timestamps in {name1} (present in {name2}):")
        for t in missing_in_df1[:10]:
            print(" ", t)
        if len(missing_in_df1) > 10:
            print(f"  ... and {len(missing_in_df1)-10} more")

    if missing_in_df2:
        print(f"\n⚠ Missing timestamps in {name2} (present in {name1}):")
        for t in missing_in_df2[:10]:
            print(" ", t)
        if len(missing_in_df2) > 10:
            print(f"  ... and {len(missing_in_df2)-10} more")

    # Overlapping timestamps
    overlap = sorted(ts1.intersection(ts2))

    if overlap:
        print(f"\n✓ Overlapping date range:")
        print(f"  Start: {overlap[0]}")
        print(f"  End:   {overlap[-1]}")
        print(f"  Total overlapping timestamps: {len(overlap)}")
    else:
        print("\n❌ No overlapping timestamps found.")

    # If both sets match perfectly
    if not missing_in_df1 and not missing_in_df2:
        print(f"\n✓ Perfect timestamp alignment between {name1} and {name2}")

    # Perform inner join (only overlapping timestamps)
    final = df1.join(df2, how="inner")

    print(f"\n✓ Final merged shape: {final.shape}")
    return final

In [352]:
final_df = merge_dataframes_wrt_time(wind_hourly, weather_hourly)

=== Timestamp Comparison: df1 vs df2 ===

✓ Overlapping date range:
  Start: 2026-01-01 00:00:00+00:00
  End:   2026-09-01 00:00:00+00:00
  Total overlapping timestamps: 5833

✓ Perfect timestamp alignment between df1 and df2

✓ Final merged shape: (5833, 18)

In [353]:
entsoe_hourly_actual_generation

,Fossil Gas [Actual Aggregated] [actual-entsoe],Fossil Hard coal [Actual Aggregated] [actual-entsoe],Fossil Oil [Actual Aggregated] [actual-entsoe],Fossil Peat [Actual Aggregated] [actual-entsoe],Hydro Pumped Storage [Actual Aggregated] [actual-entsoe],Hydro Run-of-river and pondage [Actual Aggregated] [actual-entsoe],Solar [Actual Aggregated] [actual-entsoe],Wind Onshore [Actual Aggregated] [actual-entsoe],Other [Actual Aggregated] [actual-entsoe],Fossil Gas [Actual Consumption] [actual-entsoe],Fossil Hard coal [Actual Consumption] [actual-entsoe],Fossil Oil [Actual Consumption] [actual-entsoe],Fossil Peat [Actual Consumption] [actual-entsoe],Hydro Pumped Storage [Actual Consumption] [actual-entsoe],Hydro Run-of-river and pondage [Actual Consumption] [actual-entsoe],Solar [Actual Consumption] [actual-entsoe],Other [Actual Consumption] [actual-entsoe]
DateTime,,,,,,,,,,,,,,,,,
2025-12-31 23:00:00+00:00,931.5525,0.0,164.3660,41.3390,0.0000,63.5170,0.0,1214.4895,0.0000,3.3350,8.7035,0.0475,0.004,0.0000,0.0,0.0,0.6530
2026-01-01 00:00:00+00:00,622.1850,0.0,170.7440,41.1315,0.0000,63.7020,0.0,1371.2055,0.0000,3.3370,8.4745,0.0475,0.004,36.8455,0.0,0.0,0.6530
2026-01-01 01:00:00+00:00,682.8620,0.0,165.2040,41.2345,0.0000,63.6360,0.0,1364.3015,0.0000,3.3350,8.4745,0.0475,0.004,225.5725,0.0,0.0,0.6520
2026-01-01 02:00:00+00:00,644.8945,0.0,0.0060,41.3045,0.0000,63.9170,0.0,1496.9755,0.0000,3.3370,8.2465,4.9035,0.004,223.4475,0.0,0.0,0.6570
2026-01-01 03:00:00+00:00,483.8105,0.0,0.0060,41.3390,0.0000,63.2685,0.0,1555.2310,0.0000,3.4860,8.5890,4.7495,0.004,220.8840,0.0,0.0,0.6550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-31 17:00:00+00:00,756.6125,0.0,191.7380,0.0000,115.9400,23.8635,0.0,1006.1390,0.0000,1.7030,14.0710,0.0025,0.766,0.0000,0.0,0.0,0.6635
2026-08-31 18:00:00+00:00,803.4485,0.0,168.7480,0.0000,216.9810,24.0000,0.0,930.2430,19.9360,2.2140,14.1850,0.0025,0.730,0.0000,0.0,0.0,0.2020
2026-08-31 19:00:00+00:00,873.8890,0.0,245.5765,0.0000,218.5945,23.9010,0.0,861.9685,18.7615,1.2045,14.2995,0.0020,0.694,0.0000,0.0,0.0,0.2030
2026-08-31 20:00:00+00:00,849.8830,0.0,282.6300,0.0000,216.3630,24.0335,0.0,905.9525,0.0000,0.6980,14.2995,0.0030,0.764,0.0000,0.0,0.0,0.4110
2026-08-31 21:00:00+00:00,829.1945,0.0,264.6810,0.0000,76.2040,17.9330,0.0,954.9470,0.0000,0.7060,13.7280,0.0030,0.694,0.0000,0.0,0.0,0.4070

In [354]:
final_df =merge_dataframes_wrt_time(entsoe_hourly_actual_generation, final_df)

=== Timestamp Comparison: df1 vs df2 ===

⚠ Missing timestamps in df1 (present in df2):
  2026-08-31 22:00:00+00:00
  2026-08-31 23:00:00+00:00
  2026-09-01 00:00:00+00:00

⚠ Missing timestamps in df2 (present in df1):
  2025-12-31 23:00:00+00:00

✓ Overlapping date range:
  Start: 2026-01-01 00:00:00+00:00
  End:   2026-08-31 21:00:00+00:00
  Total overlapping timestamps: 5830

✓ Final merged shape: (5830, 35)

In [355]:
final_df = merge_dataframes_wrt_time(entsoe_hourly_forecasted_wind_solar, final_df)

=== Timestamp Comparison: df1 vs df2 ===

⚠ Missing timestamps in df2 (present in df1):
  2025-12-31 23:00:00+00:00

✓ Overlapping date range:
  Start: 2026-01-01 00:00:00+00:00
  End:   2026-08-31 21:00:00+00:00
  Total overlapping timestamps: 5830

✓ Final merged shape: (5830, 36)

In [356]:
final_df = merge_dataframes_wrt_time(entsoe_hourly_load, final_df)

=== Timestamp Comparison: df1 vs df2 ===

⚠ Missing timestamps in df1 (present in df2):
  2026-08-30 23:00:00+00:00
  2026-08-31 00:00:00+00:00
  2026-08-31 01:00:00+00:00
  2026-08-31 02:00:00+00:00
  2026-08-31 03:00:00+00:00
  2026-08-31 04:00:00+00:00
  2026-08-31 05:00:00+00:00
  2026-08-31 06:00:00+00:00
  2026-08-31 07:00:00+00:00
  2026-08-31 08:00:00+00:00
  ... and 13 more

⚠ Missing timestamps in df2 (present in df1):
  2025-12-31 23:00:00+00:00

✓ Overlapping date range:
  Start: 2026-01-01 00:00:00+00:00
  End:   2026-08-30 22:00:00+00:00
  Total overlapping timestamps: 5807

✓ Final merged shape: (5807, 37)

In [357]:
final_df = merge_dataframes_wrt_time(entsoe_hourly_load_forecast, final_df)

=== Timestamp Comparison: df1 vs df2 ===

⚠ Missing timestamps in df2 (present in df1):
  2025-12-31 23:00:00+00:00
  2026-08-30 23:00:00+00:00
  2026-08-31 00:00:00+00:00
  2026-08-31 01:00:00+00:00
  2026-08-31 02:00:00+00:00
  2026-08-31 03:00:00+00:00
  2026-08-31 04:00:00+00:00
  2026-08-31 05:00:00+00:00
  2026-08-31 06:00:00+00:00
  2026-08-31 07:00:00+00:00
  ... and 14 more

✓ Overlapping date range:
  Start: 2026-01-01 00:00:00+00:00
  End:   2026-08-30 22:00:00+00:00
  Total overlapping timestamps: 5807

✓ Final merged shape: (5807, 38)

In [358]:
final_df.to_csv(f"final_wind_weather_{Year}.csv", index=True)

PermissionError: [Errno 13] Permission denied: 'final_wind_weather_2026.csv'

In [ ]:
print(final_df.columns)

Index(['Forecasted Load [forecast-entsoe]', 'Actual Load [actual-entsoe]',
       'Wind Onshore [forecast-entsoe]',
       'Fossil Gas [Actual Aggregated] [actual-entsoe]',
       'Fossil Hard coal [Actual Aggregated] [actual-entsoe]',
       'Fossil Oil [Actual Aggregated] [actual-entsoe]',
       'Fossil Peat [Actual Aggregated] [actual-entsoe]',
       'Hydro Pumped Storage [Actual Aggregated] [actual-entsoe]',
       'Hydro Run-of-river and pondage [Actual Aggregated] [actual-entsoe]',
       'Solar [Actual Aggregated] [actual-entsoe]',
       'Wind Onshore [Actual Aggregated] [actual-entsoe]',
       'Other [Actual Aggregated] [actual-entsoe]',
       'Fossil Gas [Actual Consumption] [actual-entsoe]',
       'Fossil Hard coal [Actual Consumption] [actual-entsoe]',
       'Fossil Oil [Actual Consumption] [actual-entsoe]',
       'Fossil Peat [Actual Consumption] [actual-entsoe]',
       'Hydro Pumped Storage [Actual Consumption] [actual-entsoe]',
       'Hydro Run-of-river and pondage [Actual Consumption] [actual-entsoe]',
       'Solar [Actual Consumption] [actual-entsoe]',
       'Other [Actual Consumption] [actual-entsoe]', 'ACTUAL WIND(MW)',
       'FORECAST WIND(MW)', 'irainfall   Rainfall indicator',
       'Precipitation Amount (mm)  ', 'ittt Dry bulb indicator',
       'Air Temperature (C)', 'iwb Wet bulb indicator',
       'Wet Bulb Temperature ©', 'Dew Point Temperature ©',
       'Vapour Pressure (hPa)    ', ' Relative Humidity (%) ',
       'Mean Sea Level Pressure (hPa)', 'itabspeed wind Speed indicator',
       'Mean Wind Speed (kt)', 'itabdir  wind dir indicator',
       'Predominant Wind Direction (deg)', 'Weekday',
       'Mean Wind Speed (km/h)'],
      dtype='str')