In [20]:
import pandas as pd

In [21]:
df_generation = pd.read_csv('./Data/generation.csv')
df_load = pd.read_csv('./Data/load.csv')
df_price = pd.read_csv('./Data/prices.csv')
# df_time = pd.read_csv('./Data/time-series-area.csv')

In [23]:
df_load

                 DateTime MapCode  TotalLoadValue
0     2026-01-01 00:00:00      GB       29075.000
1     2026-01-01 00:30:00      GB       28023.000
2     2026-01-01 01:00:00      GB       29204.000
3     2026-01-01 01:30:00      GB       30133.000
4     2026-01-01 02:00:00      GB       28930.000
...                   ...     ...             ...
2950  2026-01-31 21:30:00      IE        4469.852
2951  2026-01-31 22:00:00      IE        4331.766
2952  2026-01-31 22:30:00      IE        4194.740
2953  2026-01-31 23:00:00      IE        4081.001
2954  2026-01-31 23:30:00      IE        4136.897

[2955 rows x 3 columns]

In [25]:
distinct_mapcodes = df_load['MapCode'].unique()
print("Distinct MapCodes:", distinct_mapcodes)
df_load_group = df_load.groupby('MapCode')

Distinct MapCodes: <StringArray>
['GB', 'IE']
Length: 2, dtype: str

In [26]:
df_load_group.get_group('GB')

                 DateTime MapCode  TotalLoadValue
0     2026-01-01 00:00:00      GB         29075.0
1     2026-01-01 00:30:00      GB         28023.0
2     2026-01-01 01:00:00      GB         29204.0
3     2026-01-01 01:30:00      GB         30133.0
4     2026-01-01 02:00:00      GB         28930.0
...                   ...     ...             ...
2848  2026-01-31 21:30:00      GB         41164.0
2849  2026-01-31 22:00:00      GB         39983.0
2850  2026-01-31 22:30:00      GB         38744.0
2851  2026-01-31 23:00:00      GB         37213.0
2852  2026-01-31 23:30:00      GB         36130.0

[1489 rows x 3 columns]

In [ ]:
# list done the missing data for the each pric

In [ ]:
# list down the missing data for each IE_SEM

In [28]:
df_load_group.get_group('IE')

                 DateTime MapCode  TotalLoadValue
51    2026-01-01 00:00:00      IE        3877.694
52    2026-01-01 00:30:00      IE        3868.898
53    2026-01-01 01:00:00      IE        3814.388
54    2026-01-01 01:30:00      IE        3714.440
55    2026-01-01 02:00:00      IE        3648.388
...                   ...     ...             ...
2950  2026-01-31 21:30:00      IE        4469.852
2951  2026-01-31 22:00:00      IE        4331.766
2952  2026-01-31 22:30:00      IE        4194.740
2953  2026-01-31 23:00:00      IE        4081.001
2954  2026-01-31 23:30:00      IE        4136.897

[1466 rows x 3 columns]

In [29]:
distinct_mapcodes = df_price['MapCode'].unique()
print("Distinct MapCodes:", distinct_mapcodes)
df_price_group = df_price.groupby('MapCode')

Distinct MapCodes: <StringArray>
['GB', 'IE_SEM']
Length: 2, dtype: str

In [31]:
df_price_group.get_group('IE_SEM')

                DateTime MapCode  Price[Currency/MWh]      UpdateTime(UTC)
1    2026-01-01 00:00:00  IE_SEM               80.000  2025-12-31 12:35:50
2    2026-01-01 01:00:00  IE_SEM               85.430  2025-12-31 12:35:50
3    2026-01-01 02:00:00  IE_SEM               84.315  2025-12-31 12:35:50
4    2026-01-01 03:00:00  IE_SEM               80.955  2025-12-31 12:35:50
5    2026-01-01 04:00:00  IE_SEM               79.600  2025-12-31 12:35:50
..                   ...     ...                  ...                  ...
740  2026-01-31 19:00:00  IE_SEM              191.455  2026-01-30 12:35:25
741  2026-01-31 20:00:00  IE_SEM              180.590  2026-01-30 12:35:25
742  2026-01-31 21:00:00  IE_SEM              137.165  2026-01-30 12:35:25
743  2026-01-31 22:00:00  IE_SEM              121.475  2026-01-30 12:35:25
744  2026-01-31 23:00:00  IE_SEM              117.945  2026-01-31 12:35:10

[744 rows x 4 columns]

In [32]:
distinct_mapcodes = df_generation['MapCode'].unique()
print("Distinct MapCodes:", distinct_mapcodes)
df_generation_group = df_generation.groupby('MapCode')

Distinct MapCodes: <StringArray>
['GB', 'IE']
Length: 2, dtype: str

In [34]:
df_generation_group.get_group('IE')

                  DateTime MapCode  ActualGenerationOutput    ProductionType
6      2026-01-28 05:00:00      IE                     0.0  Fossil Hard coal
3927   2026-01-28 05:30:00      IE                     0.0  Fossil Hard coal
3928   2026-01-28 06:00:00      IE                     0.0  Fossil Hard coal
3929   2026-01-28 06:30:00      IE                     0.0  Fossil Hard coal
3930   2026-01-28 07:00:00      IE                     0.0  Fossil Hard coal
...                    ...     ...                     ...               ...
19463  2026-01-28 02:30:00      IE                     0.0  Fossil Hard coal
19464  2026-01-28 03:00:00      IE                     0.0  Fossil Hard coal
19465  2026-01-28 03:30:00      IE                     0.0  Fossil Hard coal
19466  2026-01-28 04:00:00      IE                     0.0  Fossil Hard coal
19467  2026-01-28 04:30:00      IE                     0.0  Fossil Hard coal

[13338 rows x 4 columns]